version: '3'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: 'dmoj'
      MYSQL_USER: 'dmoj'
      MYSQL_PASSWORD: 'ChangeMe!'
      MYSQL_ROOT_PASSWORD: 'ChangeMe!'
  redis:
    image: redis:alpine
    restart: always
  web:
    build: .
    command: /code/.docker/boot.sh
    environment:
      - DEBUG=1
      - SECRET_KEY=ChangeMe
      - SQL_DATABASE_NAME=dmoj
      - SQL_DATABASE_USER=dmoj
      - 'SQL_DATABASE_PASSWORD=ChangeMe!'
      - SQL_DATABASE_HOST=db
      - SQL_DATABASE_PORT=3306
    volumes:
      - /tmp/log:/log
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
