version: '3.7'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: 'dmoj'
      MYSQL_USER: 'dmoj'
      MYSQL_PASSWORD: 'ChangeMe!'
      MYSQL_ROOT_PASSWORD: 'ChangeMe!'
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=ChangeMe
      - SQL_DATABASE=dmoj
      - SQL_USER=dmoj
      - 'SQL_PASSWORD=ChangeMe!'
      - SQL_HOST=db
      - SQL_PORT=3306
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
